<<<<<<< HEAD
fail_builds: true                  # Fallar el build si hay vulnerabilidades
severity_threshold: medium         # Detectar vulnerabilidades desde severidad media
owasp_top_10: true                 # Activar análisis basado en OWASP Top 10
ignore_dirs:                       # Directorios que no se analizarán
  - "node_modules"
  - "venv"
ignore_paths:                      # Ignorar rutas específicas
  - "**/*.md"
  - "docs/**"
=======
fail_builds: true                  
severity_threshold: medium         
>>>>>>> fddbfb95edd3d0e0feafb11648326e1b69960816
