fail_builds: true  # Fallar el build si se encuentra una vulnerabilidad
severity_threshold: high  # Reportar solo vulnerabilidades de alta severidad
ignore_dirs: ["data"]  # Ignorar directorios específicos
